// <auto-generated />
namespace MusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class loginmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202002242011048_loginmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
